[program:gipf_overnight]
environment=PROC_NAME="%(program_name)s"
command=/workspace/gipf/ops/overnight.sh
autostart=false
autorestart=false
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
stopwaitsecs=35
