[program:gipf_final_training]
environment=PROC_NAME="%(program_name)s",GIPF_FINAL_SOURCE="runs/pilot_resnet32/latest.pt"
command=/workspace/gipf/ops/final.sh
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopwaitsecs=45

[program:gipf_final_mlp]
environment=PROC_NAME="%(program_name)s"
command=/workspace/gipf/ops/final_mlp.sh
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopwaitsecs=45

[program:gipf_league]
environment=PROC_NAME="%(program_name)s"
command=/workspace/gipf/ops/league.sh
autostart=true
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopwaitsecs=20
