[program:gipf_geometry_pilots]
environment=PROC_NAME="%(program_name)s"
command=/workspace/gipf/ops/geometry_pilots.sh
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopwaitsecs=45
